# Generated by Django 3.0 on 2020-01-23 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_supportedlanguages'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='from_lang',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='from_langs', to='posts.SupportedLanguages'),
        ),
        migrations.AddField(
            model_name='post',
            name='to_lang',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='to_langs', to='posts.SupportedLanguages'),
        ),
    ]
