# Generated by Django 3.0 on 2020-01-23 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20200122_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportedlanguages',
            name='name',
            field=models.CharField(default=models.CharField(max_length=5, unique=True), max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='from_lang',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='from_langs', to='posts.SupportedLanguages'),
        ),
        migrations.AlterField(
            model_name='post',
            name='to_lang',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='to_langs', to='posts.SupportedLanguages'),
        ),
    ]
