# Generated by Django 3.0 on 2020-01-23 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20200122_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportedlanguages',
            name='name',
        ),
    ]
