# Generated by Django 3.0 on 2020-01-23 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_remove_supportedlanguages_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportedlanguages',
            name='name',
            field=models.CharField(default='temp', max_length=15),
            preserve_default=False,
        ),
    ]
