# Generated by Django 3.0 on 2020-01-23 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_remove_supportedlanguages_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportedlanguages',
            name='name',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
