# Generated by Django 3.0 on 2020-03-11 18:13

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_auto_20200122_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body_text',
            field=tinymce.models.HTMLField(),
        ),
    ]
