# Generated by Django 3.0 on 2020-05-29 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_auto_20200529_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmemberinteractioninformation',
            name='post_member',
        ),
    ]
