# Generated by Django 3.0 on 2020-05-29 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_remove_postmemberinteractioninformation_post_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmembers',
            name='post_info',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.PostMemberInteractionInformation'),
        ),
    ]
