# Generated by Django 3.0 on 2020-05-30 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0022_postmembers_post_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmembers',
            name='post_info',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foobar', to='posts.PostMemberInteractionInformation'),
        ),
    ]
