# Generated by Django 3.0 on 2020-05-30 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0023_auto_20200529_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmembers',
            name='post_info',
        ),
        migrations.AddField(
            model_name='postmemberinteractioninformation',
            name='post_member',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foobar', to='posts.PostMembers'),
        ),
        migrations.AlterField(
            model_name='postmemberinteractioninformation',
            name='double_clicks',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='postmemberinteractioninformation',
            name='single_clicks',
            field=models.TextField(),
        ),
    ]
