# Generated by Django 3.0 on 2020-05-30 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0024_auto_20200529_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmemberinteractioninformation',
            name='post_member',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_info', to='posts.PostMembers'),
        ),
    ]
