# Generated by Django 3.0.7 on 2020-06-10 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0025_auto_20200529_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportedlanguages',
            name='ISO639_1',
            field=models.CharField(default='en-US', max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='to_lang',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='to_langs', to='posts.SupportedLanguages'),
        ),
        migrations.AlterField(
            model_name='supportedlanguages',
            name='code',
            field=models.CharField(max_length=2, unique=True),
        ),
    ]
