# Generated by Django 3.0.7 on 2020-06-10 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0026_auto_20200610_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportedlanguages',
            name='ISO639_1',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
