# Generated by Django 3.0.7 on 2020-06-11 15:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0027_auto_20200610_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='clicks_to_complete',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
