# Generated by Django 3.0 on 2019-12-30 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='creation_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
